version: '3'
services:
  nginx:
    image: docker.genya0407.net/articles_static:${TAG}
    ports:
      - "127.0.0.1:${PORT:?err}:80"
    links:
      - web
  web:
    image: docker.genya0407.net/articles_web:${TAG}
    command: articles-exe
    restart: always

